server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/edts
    username: edts
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: 172.31.221.22
    port: 6379

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG